#!/usr/bin/env bash

length=$(wc -L < input)
while IFS= read -r line; do
    printf '%0*d\n' "$length" "$line"
done < input > input.padded

sort -df < input.padded > input.sorted

while IFS= read -r num1; do
    while IFS= read -r num2; do
        num3=$((2020 - 10#${num1} - 10#${num2}))
        if ((num3 >= 0)); then
            num3Padded=$(printf '%0*d\n' "$length" "$num3")
            if look -df "$num3Padded" input.sorted; then
                printf '%s\n%s\n\n%d\n' "$num1" "$num2" "$((10#${num1} * 10#${num2} * num3))"
                exit
            fi
        fi
    done < input.sorted
done < input.sorted

printf >&2 '%s: no solution found\n' "$0"
exit 1
