#!/usr/bin/gawk -f

BEGIN {
    FS = ""
}

/./ {
    for (i = 1; i <= NF; i++) {
        answers[$i] = 1
    }
}

function summarize_answers(    len) {
    len = length(answers)
    print len > "/dev/stderr"
    sum += len
    delete answers
}

/^$/ {
    summarize_answers()
}

ENDFILE {
    summarize_answers()

    print sum
    sum = 0
}
