#!/usr/bin/gawk -f

BEGIN {
    FS = ""
}

/./ {
    for (i = 1; i <= NF; i++) {
        answers[$i]++
    }
    answerers++
}

function summarize_answers(    len, i) {
    # part 1
    len = length(answers)
    # part 2
    len = 0
    for (i in answers) {
        if (answers[i] == answerers) {
            len++
        }
    }

    print len > "/dev/stderr"
    sum += len
    delete answers
    answerers = 0
}

/^$/ {
    summarize_answers()
}

ENDFILE {
    summarize_answers()

    print sum
    sum = 0
}
