#!/usr/bin/env bash

function waiting_time {
    local departure=$1
    local my_departure=$2
    printf '%d' "$((departure - (my_departure % departure)))"
}

function part1 {
    local IFS
    {
        IFS= read -r my_departure
        IFS= read -r departures
    } < "$1"
    IFS=,
    for departure in $departures; do
        if [[ $departure == 'x' ]]; then
            continue
        fi
        waiting_time=$(waiting_time "$departure" "$my_departure")
        if [[ ! -v shortest_waiting_time ]] || ((waiting_time < shortest_waiting_time)); then
            earliest_departure=$departure
            shortest_waiting_time=$waiting_time
        fi
    done
    printf '%d\n' "$((earliest_departure * shortest_waiting_time))"
}

function part2_bruteforce_bash {
    local IFS
    {
        IFS= read -r _ignored
        IFS= read -r departures_line
    } < "$1"
    IFS=,
    departures_by_offset=($departures_line)
    offsets_by_departure=()
    for offset in "${!departures_by_offset[@]}"; do
        departure=${departures_by_offset["$offset"]}
        if [[ $departure == 'x' ]]; then
            continue;
        fi
        offsets_by_departure["$departure"]=$offset
        if [[ ! -v last_departure ]] || ((departure > last_departure)); then
            last_departure=$departure
        fi
    done
    last_departure_offset=${offsets_by_departure["$last_departure"]}
    for ((i=0; ; i++)); do
        t=$((i * last_departure + last_departure - last_departure_offset))
        for departure in "${!offsets_by_departure[@]}"; do
            if [[ $departure == $last_departure ]]; then
                continue
            fi
            offset=${offsets_by_departure["$departure"]}
            if (((t + offset) % departure)); then
                continue 2
            fi
        done
        printf '%s\n' "$t"
        break
    done
}

function part2_bruteforce_rust {
    cargo run --release --quiet -- "$1"
}

function part2_chinese_remainder_theorem {
    {
        IFS= read -r _ignored
        IFS=, read -a inputs
    } < "$1"

    a_i=()
    m_i=()
    M=1
    for ((i=0; i<${#inputs[@]}; i++)); do
        if [[ ${inputs[$i]} == 'x' ]]; then
            continue
        fi
        let m_i[i]=inputs[i]
        let a_i[i]=(m_i[i] - i)
        let M*=m_i[i]
    done

    M_i=()
    for i in "${!m_i[@]}"; do
        let M_i[i]=M/m_i[i]
    done

    x=0
    for i in "${!m_i[@]}"; do
        read -r d r_i s_i < <(extended_euklid "${m_i[$i]}" "${M_i[$i]}")
        if ((d != 1)); then
            printf >&2 '%s: extended_euklid returned d ≠ 1 (%d), inputs are not coprime\n' "$0" "$d"
            return 1
        fi
        let e_i=(s_i * M_i[i])
        let x+=(a_i[i] * e_i)
    done
    let x=(x % M)
    if ((x < 0)); then
        let x+=M
    fi
    printf '%s\n' "$x"
}

# extended_euklid a b
# prints d s t, such that
# d = s * a + b * t
function extended_euklid {
    if (($2 == 0)); then
        printf '%d 1 0\n' "$1"
    else
        read -r d_ s_ t_ < <(extended_euklid "$2" "$(($1 % $2))")
        printf '%d %d %d\n' "$d_" "$t_" "$((s_ - ($1 / $2) * t_))"
    fi
}

part1 "${1:?input file required}"
# part2_bruteforce_bash "${1:?input file required}"
# part2_bruteforce_rust "${1:?input file required}"
part2_chinese_remainder_theorem "${1:?input file required}"
