#!/usr/bin/env bash

function waiting_time {
    local departure=$1
    local my_departure=$2
    printf '%d' "$((departure - (my_departure % departure)))"
}

function part1 {
    local IFS
    {
        IFS= read -r my_departure
        IFS= read -r departures
    } < "$1"
    IFS=,
    for departure in $departures; do
        if [[ $departure == 'x' ]]; then
            continue
        fi
        waiting_time=$(waiting_time "$departure" "$my_departure")
        if [[ ! -v shortest_waiting_time ]] || ((waiting_time < shortest_waiting_time)); then
            earliest_departure=$departure
            shortest_waiting_time=$waiting_time
        fi
    done
    printf '%d\n' "$((earliest_departure * shortest_waiting_time))"
}

function part2_bruteforce_bash {
    local IFS
    {
        IFS= read -r _ignored
        IFS= read -r departures_line
    } < "$1"
    IFS=,
    departures_by_offset=($departures_line)
    offsets_by_departure=()
    for offset in "${!departures_by_offset[@]}"; do
        departure=${departures_by_offset["$offset"]}
        if [[ $departure == 'x' ]]; then
            continue;
        fi
        offsets_by_departure["$departure"]=$offset
        if [[ ! -v last_departure ]] || ((departure > last_departure)); then
            last_departure=$departure
        fi
    done
    last_departure_offset=${offsets_by_departure["$last_departure"]}
    for ((i=0; ; i++)); do
        t=$((i * last_departure + last_departure - last_departure_offset))
        for departure in "${!offsets_by_departure[@]}"; do
            if [[ $departure == $last_departure ]]; then
                continue
            fi
            offset=${offsets_by_departure["$departure"]}
            if (((t + offset) % departure)); then
                continue 2
            fi
        done
        printf '%s\n' "$t"
        break
    done
}

function part2_bruteforce_rust {
    cargo run --release --quiet -- "$1"
}

part1 "${1:?input file required}"
part2_bruteforce_bash "${1:?input file required}"
part2_bruteforce_rust "${1:?input file required}"
