#!/usr/bin/env bash

function part1 {
    sort -n -- "$1" | awk '
        {
            diffs[$1-prev]++;
            prev=$1
        }
        
        END {
            diffs[3]++;
            print diffs[1] * diffs[3];
        }
    '
}

function part2 {
    sort -n -- "$1" | awk '
        BEGIN {
            arrangements[0] = 1;
        }

        {
            lastArrangements \
                = arrangements[$1] \
                = arrangements[$1 - 1] \
                + arrangements[$1 - 2] \
                + arrangements[$1 - 3];
        }

        END {
            print lastArrangements;
        }
    '
}

for input; do
    part1 "$input"
    part2 "$input"
done
