#!/usr/bin/env bash

function part1 {
    sort -n -- "$1" | awk '
        {
            diffs[$1-prev]++;
            prev=$1
        }
        
        END {
            diffs[3]++;
            print diffs[1] * diffs[3];
        }
    '
}

for input; do
    part1 "$input"
done
