#!/usr/bin/awk -f

BEGIN {
    FS = "[- :]";
}

{
    char = $3
    posA = $1
    posB = $2
    password = $5

    charA = substr(password, posA, 1)
    charB = substr(password, posB, 1)

    if ((charA == char) != (charB == char)) {
        print "matches " $0
    } else {
        print "does not match " $0 > "/dev/stderr"
    }
}
